In [1]:
import pandas as pd
df = pd.read_excel(r"C:\Users\KEYUR\Desktop\data cleaning\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [2]:
df.drop(columns="Not_Useful_Column",inplace=True)

In [3]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       21 non-null     int64
 1   First_Name       21 non-null     object
 2   Last_Name        20 non-null     object
 3   Phone_Number     19 non-null     object
 4   Address          21 non-null     object
 5   Paying Customer  21 non-null     object
 6   Do_Not_Contact   17 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.3+ KB

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [7]:
df["Last_Name"]=df["Last_Name"].str.strip()
df["Last_Name"]=df["Last_Name"].str.lstrip("./")
df["Last_Name"]=df["Last_Name"].str.strip("./123_")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [8]:
df.head(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No

In [9]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No

# cleaning phone number col

In [11]:
import re
import pandas as pd
import numpy as np
def clean_phone(x):
    x = str(x)  
    x = re.sub(r'\D', '', x)  
    if len(x) == 10:  
        return f"{x[:3]}-{x[3:6]}-{x[6:]}"
    else:
        return np.nan  

df["Phone_Number"] = df["Phone_Number"].apply(clean_phone)

print(df)
df

    CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421
1         1002       Abed       Nadir  123-643-9775
2         1003     Walter       White  706-695-0392
3         1004     Dwight     Schrute  123-543-2345
4         1005        Jon        Snow  876-678-3469
5         1006        Ron     Swanson  304-762-2467
6         1007       Jeff      Winger           NaN
7         1008   Sherlock      Holmes  876-678-3469
8         1009    Gandalf         NaN           NaN
9         1010      Peter      Parker  123-545-5421
10        1011    Samwise      Gamgee           NaN
11        1012      Harry      Potter  706-695-0392
12        1013        Don      Draper  123-543-2345
13        1014     Leslie       Knope  876-678-3469
14        1015       Toby  Flenderson  304-762-2467
15        1016        Ron     Weasley  123-545-5421
16        1017   Michael        Scott  123-643-9775
17        1018      Clark        Kent  706-695-0392
18        1019      Creed      Braton           NaN
19        1020     Anakin   Skywalker  876-678-3469

                                  Address Paying Customer Do_Not_Contact
0                   123 Shire Lane, Shire             Yes             No
1                     93 West Main Street              No            Yes
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                        123 Dragons Road               Y             No
5                        768 City Parkway             Yes            Yes
6                       1209 South Street              No             No
7                           98 Clue Drive               N             No
8                        123 Middle Earth             Yes            NaN
9              25th Main Street, New York             Yes             No
10                  612 Shire Lane, Shire             Yes             No
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street             Yes              N
13                       343 City Parkway             Yes             No
14                          214 HR Avenue               N             No
15                   2395 Hogwarts Avenue              No              N
16         121 Paper Avenue, Pennsylvania             Yes             No
17                        3498 Super Lane               Y            NaN
18                                    N/a             N/a            Yes
19            910 Tatooine Road, Tatooine             Yes              N

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,NaN,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,NaN,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [12]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,NaN,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,NaN,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [13]:
df[["street_Address","state","zipcode"]]=df["Address"].str.split(",",expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zipcode
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,NaN,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,NaN,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [14]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("Yes","Y")
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("No","N")

In [15]:
df["Paying Customer"]=df["Paying Customer"].str.replace("Yes","Y")
df["Paying Customer"]=df["Paying Customer"].str.replace("No","N")

In [16]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zipcode
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,NaN,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,NaN,N/a,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [17]:
df.fillna("",inplace=True)
df.replace("N/a","")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zipcode
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [18]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zipcode
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [19]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"]=="Y":
        df.drop(x,inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zipcode
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [48]:
for x in df.index:
    if df.loc[x,"Phone_Number"]==" ":
        df.drop(x,inplace=True)
df

,level_0,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zipcode
0,0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1,2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,298 Drugs Driveway,,
2,2,4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
4,4,7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
6,6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
8,8,11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
9,9,12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
10,10,13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
11,11,14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
12,12,15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
13,13,16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
14,14,17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,3498 Super Lane,,
15,15,19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [68]:
# df = df.rename(columns={'level_0': 'old_index'}).reset_index()
# df.drop(columns=["old_index","index"],inplace=True)
# df.drop(columns="zipcode",inplace=True)

KeyError: "['zipcode'] not found in axis"

In [70]:
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire
1,1,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,298 Drugs Driveway,
2,2,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,
3,3,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,
4,4,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York
5,5,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,
6,6,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,
7,7,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,
8,8,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,
9,9,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,
10,10,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania
11,11,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,3498 Super Lane,
12,12,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine